server:
  port: 8081
spring:
  application:
    name: MultiTenant
  datasource:
    url: 'jdbc:postgresql://localhost:5432/multitenant'
    username: 'postgres'
    password: 'sharath9'
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
  main:
    allow-circular-references: true